# Generated by Django 5.2.9 on 2025-12-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('semestre', models.CharField(default='2025-1', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
