# Generated by Django 5.2.9 on 2025-12-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nivelacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaComentario',
            new_name='RegistroMateria',
        ),
    ]
